### ISSUE TITLE
License Type Double Check + Document

### ISSUE THREAD

**Issue by huuquangnhatnguyen** [AIconic5001/Kalliope#18]
Check what type of license we can use to train AI

**Comment by huuquangnhatnguyen** [comment]
[Prompt 1.txt](https://github.com/user-attachments/files/17122950/Prompt.1.txt)

Testing 5 paragraphs with 5 fields. (2 assignees)

**Comment by Huy-Le2** [comment]
[Licenses for Research Data.docx](https://github.com/user-attachments/files/17171766/Licenses.for.Research.Data.docx)
License guide
